server:
   address: 0.0.0.0
   port: 8090

spring:
  application:
    name: Temporal Server Demonstration

  temporal:
    namespace: donald-demo.sdvdw
    workersAutoDiscovery:
      packages: 
        - com.donald.demo.temporaldemoserver
    connection:
      target: donald-demo.sdvdw.tmprl.cloud:7233
      mtls:
        key-file: /Users/donald/stuff/source/certificates/temporal-client.key
        cert-chain-file: /Users/donald/stuff/source/certificates/temporal-client-leaf.pem
    # (Note following configuration are not set by default but serve more as reference)
    workers:
      - task-queue: HelloDemoTaskQueue
        name: HelloDemoWorker
        workflow-classes:
          - com.donald.demo.temporaldemoserver.hello.HelloWorkflowImpl
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:                                   #  server side rate limiting
          max-worker-activities-per-second: 3
          max-task-queue-activities-per-second: 3

      - task-queue: TransferMoneyDemoTaskQueue
        name: TransferDemoWorker
        workflow-classes:
          - com.donald.demo.temporaldemoserver.transfermoney.TransferMoneyWorkflowImpl

      - task-queue: ManageNamespaceWFTaskQueue
        name: OpsWFDemoWorker
        workflow-classes:
          - com.donald.demo.temporaldemoserver.namespace.workflows.ManageNamespaceImpl
      - task-queue: ManageNamespaceActivityTaskQueue
        name: OpsActivityDemoWorker
        workflow-classes:
        activity-beans:
        #   - HelloActivityImpl
        #   - AccountTransferActivities
                                               
    workflow-cache:  
      max-instances: 100
      max-threads: 100

